### ISSUE TITLE
Will this be updated for the latest foundry?

### ISSUE THREAD

**Issue by tbrockwood** [kid2407/DungeonScrawlImporter#1]
I tried to use this on the 0.9 and 0.8.9 versions of Foundry, but it never works. Well, it goes through the import and says it's successful, but I don't see a new scene. Perhaps I'm doing it wrong, or does it just not work with newer Foundry?

**Comment by kid2407** [comment]
Good Morning,

it does not create a new scene bur rather places the walls on the active scene. So you create a scene of an appropriate size then start the import, which should populate the walls layer.
Since the only thing I do is read a file and set walls it should work regardless of versions, though I guess I should bump up the compatible version number in that case ^^

**Comment by tbrockwood** [comment]
> 

when I export a map from Dungescrawl, what are the best settings to use? For example, I just exported a simple square shaped map to test it. I set it to 70px per cell , and had it export the screen (and not a selected rectangle). Once imported, the walls were the right shape, but made a square of about twice the area of the actual map.

**Comment by kid2407** [comment]
The scaling might be broken then. Could you attach the exported file from Dungeonscrawl as well as the exported scene from Foundry?

**Comment by tbrockwood** [comment]
Sure, here's the export and .ds
[Downloads.zip](https://github.com/kid2407/DungeonScrawlImporter/files/8110385/Downloads.zip)

**Comment by tbrockwood** [comment]
If this helps, here's a screencap of the scene after the import.
![post import](https://user-images.githubusercontent.com/7917947/154985603-da525482-b475-40ab-b6cf-734cae68baf2.jpg)

**Comment by tbrockwood** [comment]
Are there any updates?

**Comment by kid2407** [comment]
So turns out it is a logic error on my side, the core functionality still works perfectly fine in v9. I just didn't think of a case that will cause the "shift by X cells" to not be triggered. I'll see i can get it fixed within a few days, _shouldn't_ be that hard, just fixing the logic bug.

**Comment by tbrockwood** [comment]
Thanks for the update!

**Comment by kid2407** [comment]
Turned out to be very stupid logic error indeed, it is now fixed with the [latest release](https://github.com/kid2407/DungeonScrawlImporter/releases/tag/1.2.0).

**Comment by tbrockwood** [comment]
Works, thanks so much!

**Comment by wintersleepAI** [comment]
![image](https://github.com/kid2407/DungeonScrawlImporter/assets/88955427/7ed8041c-9623-4665-98a7-357be100941c)
trying with v11 1.5.0 and it looks like something similar is happening on import. downloaded the png, set up a scene to the dimensions from the downloader, the used the scrawl importer to add the walls and the alignment seems off
