### ISSUE TITLE
Went to install Module on Foundry and got this error?

### ISSUE THREAD

**Issue by QueenStephen** [kid2407/DungeonScrawlImporter#2]
![error](https://user-images.githubusercontent.com/119106162/204082850-6b237a3d-61a5-42ec-a8ae-500812dcffe7.png)
I tried to install this from within foundry and this is the error I get and it wont install would you have any advice on how to fix this?

**Comment by kid2407** [comment]
I knew something would go wrong xD

Fixed in the latest release, [Version 1.3.1](https://github.com/kid2407/DungeonScrawlImporter/releases/tag/1.3.1)
