### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by loftusjl** [kid2407/DungeonScrawlImporter#3]
Just updated Foundry to version 10, build 291. Went to install Dungeon Scrawl Importer and am getting the below error:
![image](https://user-images.githubusercontent.com/35356853/206921312-6d6973b5-3058-4e80-9787-9cd83eb22ed1.png)
![image](https://user-images.githubusercontent.com/35356853/206921331-ca24a638-97c6-4691-8298-7034ca0b330f.png)

**Comment by PepijnMC** [comment]
The package listing on Foundry was never updated for 1.3.1, so it's still trying to download the faulty 1.3.0 release with missing library files.

**Comment by kid2407** [comment]
Oh my... it should now be fixed, I made sure to add the correct version via the foundry package administration.
