### ISSUE TITLE
Not updated to v11 and does not show import button

### ISSUE THREAD

**Issue by Rykazz** [kid2407/DungeonScrawlImporter#5]
The module is not update to foundry v11, and when I install the v10 version (1.3.1) and activate it, I can not find any way to import a map from DS.

**Comment by anders-tech** [comment]
^ Experiencing the same issue

**Comment by kid2407** [comment]
One update later we have a working release, will be available fro within Foundry shortly: https://github.com/kid2407/DungeonScrawlImporter/releases/tag/1.4.0
